CREATE TABLE user_account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE lunch_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(16) NOT NULL UNIQUE,
  created_by BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL,
  picked_restaurant VARCHAR(200),
  created_at TIMESTAMP NOT NULL,
  ended_at TIMESTAMP,
  version BIGINT NOT NULL,
  CONSTRAINT fk_session_user FOREIGN KEY (created_by) REFERENCES user_account(id)
);

CREATE TABLE session_participant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  joined_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_part_session FOREIGN KEY (session_id) REFERENCES lunch_session(id),
  CONSTRAINT fk_part_user FOREIGN KEY (user_id) REFERENCES user_account(id),
  CONSTRAINT uq_session_user UNIQUE(session_id, user_id)
);

CREATE TABLE restaurant_submission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  restaurant_name VARCHAR(200) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_sub_session FOREIGN KEY (session_id) REFERENCES lunch_session(id),
  CONSTRAINT fk_sub_user FOREIGN KEY (user_id) REFERENCES user_account(id),
  CONSTRAINT uq_session_restaurant UNIQUE(session_id, restaurant_name)
);

